### PR TITLE
Release/1.1.0

### PR DESCRIPTION
**Pull request by peel**

### CODE REVIEW

**Comment by benjben** [comment]
@peel this PR makes me wonder something related to Gitflow: the code of `release/` PRs will have already been reviewed in `feature/` PRs. For instance the code to review in this PR has already been reviewed in #10 #12 ? So what should we focus on in `release/` PRs?

**Comment by peel** [comment]
@benjben from my previous experience this is generally a scoping PR and there's really not much to review and has been used to spread understanding on what we're about to share.

**Comment by dilyand** [comment]
I guess one thing to review here is that the `CHANGELOG` matches the release milestone.

**Review by dilyand — COMMENTED** [review]
LGTM.

I think though that #18 shouldn't be a separate issue, since it does not represent a change from the previous version. It belongs in #6. The two commits should also be squashed.

**Comment by peel** [comment]
Definitely from release standpoint it makes sense to merge them. The only downside is that rebasing back into `develop` will not be really gitflow-friendly as it will cause conflicts and I'll have to either create a merge commit or force push a shared `develop` branch. But that brings the point of releasing snapshots from feature branches even more important so we don't need to deal with that.

**Review by dilyand — APPROVED** [review]
👍🏻

**Comment by chuwy** [comment]
> I think though that #18 shouldn't be a separate issue

Agree with @dilyand. CHANGELOG is user-facing and our dev flow should work to reflect/maintain it, not vice-versa (CHANGELOG reflecting the dev flow)

**Pull request merged**
